---
title: "[Q#156508][A#156889] Closing a Java FileInputStream"
question_title: "Closing a Java FileInputStream"
question_text: "Alright, I have been doing the following (variable names have been changed): Recently, I started using FindBugs, which suggests that I am not properly closing streams.  I decide to see if there's anything that can be done with a finally{} block, and then I see, oh yeah, close() can throw IOException.  What are people supposed to do here?  The Java libraries throw too many checked exceptions."
answer_text: "For Java 7 and above try-with-resources should be used: If you're stuck on Java 6 or below... This pattern avoids mucking around with null: For a more detail on how to effectively deal with close, read this blog post: Java: how not to make a mess of stream handling. It has more sample code, more depth and covers the pitfalls of wrapping close in a catch block."
apization_code: "package com.stackoverflow.api;  import java.io.FileInputStream; import java.io.IOException; import java.io.InputStream;  /**  * Closing a Java FileInputStream  *  * @author APIzator  * @see <a href=\"https://stackoverflow.com/a/156889\">https://stackoverflow.com/a/156889</a>  */ public class APIzator156889 {    public static void closeFileinputstream(String file) throws Exception {     try (InputStream in = new FileInputStream(file)) {       // TODO: work     } catch (IOException e) {       // TODO: handle error     }     try {       InputStream in = new FileInputStream(file);       try {         // TODO: work       } finally {         in.close();       }     } catch (IOException e) {       // TODO: error handling     }   } }"
---

https://stackoverflow.com/q/156508

Alright, I have been doing the following (variable names have been changed):
Recently, I started using FindBugs, which suggests that I am not properly closing streams.  I decide to see if there&#x27;s anything that can be done with a finally{} block, and then I see, oh yeah, close() can throw IOException.  What are people supposed to do here?  The Java libraries throw too many checked exceptions.


<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
FileInputStream fis = null;
try
{
    fis = new FileInputStream(file);

    ... process ...

}
catch (IOException e)
{
    ... handle error ...
}
finally
{
    if (fis != null)
        fis.close();
}
```


## Original code snippet

https://stackoverflow.com/a/156889

For Java 7 and above try-with-resources should be used:
If you&#x27;re stuck on Java 6 or below...
This pattern avoids mucking around with null:
For a more detail on how to effectively deal with close, read this blog post: Java: how not to make a mess of stream handling. It has more sample code, more depth and covers the pitfalls of wrapping close in a catch block.

<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
try (InputStream in = new FileInputStream(file)) {
  // TODO: work
} catch (IOException e) {
  // TODO: handle error
}
try {
        InputStream in = new FileInputStream(file);
        try {
            // TODO: work
        } finally {
            in.close();
        }
    } catch (IOException e) {
        // TODO: error handling
    }
```

## Produced APIzation

[`APIzator156889.java`](https://github.com/pasqualesalza/apization/raw/main/data/search/APIzator156889.java)

<div class="code-logo"><img src="/apizator.png" /></div>

```java
package com.stackoverflow.api;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

/**
 * Closing a Java FileInputStream
 *
 * @author APIzator
 * @see <a href="https://stackoverflow.com/a/156889">https://stackoverflow.com/a/156889</a>
 */
public class APIzator156889 {

  public static void closeFileinputstream(String file) throws Exception {
    try (InputStream in = new FileInputStream(file)) {
      // TODO: work
    } catch (IOException e) {
      // TODO: handle error
    }
    try {
      InputStream in = new FileInputStream(file);
      try {
        // TODO: work
      } finally {
        in.close();
      }
    } catch (IOException e) {
      // TODO: error handling
    }
  }
}

```