---
title: "[Q#17405714][A#17405806] Java How do you return a value from try,catch, and finally?"
question_title: "Java How do you return a value from try,catch, and finally?"
question_text: "So when I do a code of blocks inside a \"try{}\", and I try to return a value, it comes out \" no return values\". This is the code I am using that represents my problem. Bascially, the question I'm having is \"How do you return a value when you are using try and catch block?"
answer_text: "To return a value when using try/catch you can use a temporary variable, e.g. Else you need to have a return in every execution path (try block or catch block) that has no throw."
apization_code: "package com.stackoverflow.api;  import org.w3c.dom.ranges.RangeException;  /**  * Java How do you return a value from try,catch, and finally?  *  * @author APIzator  * @see <a href=\"https://stackoverflow.com/a/17405806\">https://stackoverflow.com/a/17405806</a>  */ public class APIzator17405806 {    public static double add(String[] values) {     double sum = 0.0;     try {       int length = values.length;       double[] arrayValues = new double[length];       for (int i = 0; i < length; i++) {         arrayValues[i] = Double.parseDouble(values[i]);         sum += arrayValues[i];       }     } catch (NumberFormatException e) {       e.printStackTrace();     } catch (RangeException e) {       throw e;     } finally {       System.out.println(\"Thank you for using the program!\");     }     return sum;   } }"
---

https://stackoverflow.com/q/17405714

So when I do a code of blocks inside a &quot;try{}&quot;, and I try to return a value, it comes out &quot; no return values&quot;. This is the code I am using that represents my problem.
Bascially, the question I&#x27;m having is &quot;How do you return a value when you are using try and catch block?


<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
import org.w3c.dom.ranges.RangeException;


public class Pg257E5 
{
public static void main(String[]args)
{

    try
    {
        System.out.println(add(args));
    }
    catch(RangeException e)
    {
        e.printStackTrace();
    }
    finally
    {
        System.out.println("Thanks for using the program kiddo!");
    }

}
public static double add(String[] values) // shows a commpile error here that I don't have a return value
{
    try
    {
        int length = values.length;
        double arrayValues[] = new double[length];
        double sum =0;
        for(int i = 0; i<length; i++)
        {
            arrayValues[i] = Double.parseDouble(values[i]);
            sum += arrayValues[i];
        }

        return sum; // I do have a return value here. Is it because if the an exception occurs the codes in try stops and doesn't get to the return value?
    }
    catch(NumberFormatException e)
    {
        e.printStackTrace();
    }
    catch(RangeException e)
    {
        throw e;
    }
    finally
    {
        System.out.println("Thank you for using the program!");// so would I need to put a return value of type double here?
    }

}
}
```


## Original code snippet

https://stackoverflow.com/a/17405806

To return a value when using try/catch you can use a temporary variable, e.g.
Else you need to have a return in every execution path (try block or catch block) that has no throw.

<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
public static double add(String[] values) {
    double sum = 0.0;
    try {
        int length = values.length;
        double arrayValues[] = new double[length];
        for(int i = 0; i < length; i++) {
            arrayValues[i] = Double.parseDouble(values[i]);
            sum += arrayValues[i];
        }
    } catch(NumberFormatException e) {
        e.printStackTrace();
    } catch(RangeException e) {
        throw e;
    } finally {
        System.out.println("Thank you for using the program!");
    }
    return sum;
}
```

## Produced APIzation

[`APIzator17405806.java`](https://github.com/pasqualesalza/apization/raw/main/data/search/APIzator17405806.java)

<div class="code-logo"><img src="/apizator.png" /></div>

```java
package com.stackoverflow.api;

import org.w3c.dom.ranges.RangeException;

/**
 * Java How do you return a value from try,catch, and finally?
 *
 * @author APIzator
 * @see <a href="https://stackoverflow.com/a/17405806">https://stackoverflow.com/a/17405806</a>
 */
public class APIzator17405806 {

  public static double add(String[] values) {
    double sum = 0.0;
    try {
      int length = values.length;
      double[] arrayValues = new double[length];
      for (int i = 0; i < length; i++) {
        arrayValues[i] = Double.parseDouble(values[i]);
        sum += arrayValues[i];
      }
    } catch (NumberFormatException e) {
      e.printStackTrace();
    } catch (RangeException e) {
      throw e;
    } finally {
      System.out.println("Thank you for using the program!");
    }
    return sum;
  }
}

```